/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mng/all': RouteRecordInfo<'/mng/all', '/mng/all', Record<never, never>, Record<never, never>>,
    '/mng/deliver': RouteRecordInfo<'/mng/deliver', '/mng/deliver', Record<never, never>, Record<never, never>>,
    '/mng/payment': RouteRecordInfo<'/mng/payment', '/mng/payment', Record<never, never>, Record<never, never>>,
    '/mng/upload': RouteRecordInfo<'/mng/upload', '/mng/upload', Record<never, never>, Record<never, never>>,
    '/welcome': RouteRecordInfo<'/welcome', '/welcome', Record<never, never>, Record<never, never>>,
  }
}
